-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2024-12-12 22:35:13 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE categorii_produse (
    id_categorie   NUMBER NOT NULL,
    nume_categorie VARCHAR2(30) NOT NULL
);

ALTER TABLE categorii_produse ADD CHECK ( length(nume_categorie) > 1 );

ALTER TABLE categorii_produse ADD CONSTRAINT categorii_produse_pk PRIMARY KEY ( id_categorie );

CREATE TABLE clienti (
    id_client NUMBER NOT NULL,
    nume      VARCHAR2(30) NOT NULL,
    prenume   VARCHAR2(30) NOT NULL,
    email     VARCHAR2(30) NOT NULL,
    telefon   VARCHAR2(15) NOT NULL
);

ALTER TABLE clienti ADD CHECK ( length(nume) > 1 );

ALTER TABLE clienti
    ADD CONSTRAINT clienti_email_ck CHECK ( REGEXP_LIKE ( email,
                                                          '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE clienti ADD CONSTRAINT clienti_pk PRIMARY KEY ( id_client );

ALTER TABLE clienti ADD CONSTRAINT clienti_email_telefon_un UNIQUE ( email,
                                                                     telefon );

ALTER TABLE clienti ADD CONSTRAINT clienti_telefon_un UNIQUE ( telefon );

ALTER TABLE clienti ADD CONSTRAINT clienti_email_un UNIQUE ( email );

CREATE TABLE comenzi (
    id_comanda        NUMBER NOT NULL,
    data_comanda      DATE NOT NULL,
    status            VARCHAR2(20) NOT NULL,
    total             NUMBER(10, 2) NOT NULL,
    clienti_id_client NUMBER NOT NULL
);

ALTER TABLE comenzi ADD CONSTRAINT comenzi_pk PRIMARY KEY ( id_comanda );

CREATE TABLE descierea_prod (
    descriere VARCHAR2(200)
);

ALTER TABLE descierea_prod ADD CONSTRAINT descierea_prod_descriere_un UNIQUE ( descriere );

CREATE TABLE produse (
    id_produs                      NUMBER NOT NULL,
    nume_produs                    VARCHAR2(100) NOT NULL,
    tip_produs                     VARCHAR2(50) NOT NULL,
    data_expirarii                 DATE NOT NULL,
    stoc                           INTEGER NOT NULL,
    categorii_produse_id_categorie NUMBER NOT NULL,
    pret_unitar                    NUMBER(10, 2) NOT NULL,
    descierea_prod_descriere       VARCHAR2(200) NOT NULL
);

ALTER TABLE produse ADD CHECK ( length(nume_produs) > 1 );

ALTER TABLE produse ADD CONSTRAINT produse_stoc_ck CHECK ( stoc >= 0 );

CREATE UNIQUE INDEX produse__idx ON
    produse (
        descierea_prod_descriere
    ASC );

ALTER TABLE produse ADD CONSTRAINT produse_pk PRIMARY KEY ( id_produs );

ALTER TABLE produse ADD CONSTRAINT produse_nume_produs_un UNIQUE ( nume_produs );

CREATE TABLE produse_comandate (
    cantitate          NUMBER NOT NULL,
    produse_id_produs  NUMBER NOT NULL,
    comenzi_id_comanda NUMBER NOT NULL
);

CREATE TABLE recenzii (
    id_recenzie       NUMBER NOT NULL,
    id_produs         NUMBER NOT NULL,
    recenzia          VARCHAR2(500) NOT NULL,
    clienti_id_client NUMBER NOT NULL,
    produse_id_produs NUMBER NOT NULL,
    data_recenzie     DATE NOT NULL
);

ALTER TABLE recenzii ADD CONSTRAINT recenzii_pk PRIMARY KEY ( id_recenzie );

ALTER TABLE comenzi
    ADD CONSTRAINT comenzi_clienti_fk FOREIGN KEY ( clienti_id_client )
        REFERENCES clienti ( id_client );

ALTER TABLE produse
    ADD CONSTRAINT produse_categorii_produse_fk FOREIGN KEY ( categorii_produse_id_categorie )
        REFERENCES categorii_produse ( id_categorie );

ALTER TABLE produse_comandate
    ADD CONSTRAINT produse_comandate_comenzi_fk FOREIGN KEY ( comenzi_id_comanda )
        REFERENCES comenzi ( id_comanda );

ALTER TABLE produse_comandate
    ADD CONSTRAINT produse_comandate_produse_fk FOREIGN KEY ( produse_id_produs )
        REFERENCES produse ( id_produs );

ALTER TABLE produse
    ADD CONSTRAINT produse_descierea_prod_fk FOREIGN KEY ( descierea_prod_descriere )
        REFERENCES descierea_prod ( descriere );

ALTER TABLE recenzii
    ADD CONSTRAINT recenzii_clienti_fk FOREIGN KEY ( clienti_id_client )
        REFERENCES clienti ( id_client );

ALTER TABLE recenzii
    ADD CONSTRAINT recenzii_produse_fk FOREIGN KEY ( produse_id_produs )
        REFERENCES produse ( id_produs );

CREATE SEQUENCE categorii_produse_id_categorie START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER categorii_produse_id_categorie BEFORE
    INSERT ON categorii_produse
    FOR EACH ROW
    WHEN ( new.id_categorie IS NULL )
BEGIN
    :new.id_categorie := categorii_produse_id_categorie.nextval;
END;
/

CREATE SEQUENCE clienti_id_client_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER clienti_id_client_trg BEFORE
    INSERT ON clienti
    FOR EACH ROW
    WHEN ( new.id_client IS NULL )
BEGIN
    :new.id_client := clienti_id_client_seq.nextval;
END;
/

CREATE SEQUENCE comenzi_id_comanda_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER comenzi_id_comanda_trg BEFORE
    INSERT ON comenzi
    FOR EACH ROW
    WHEN ( new.id_comanda IS NULL )
BEGIN
    :new.id_comanda := comenzi_id_comanda_seq.nextval;
END;
/

CREATE SEQUENCE produse_id_produs_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER produse_id_produs_trg BEFORE
    INSERT ON produse
    FOR EACH ROW
    WHEN ( new.id_produs IS NULL )
BEGIN
    :new.id_produs := produse_id_produs_seq.nextval;
END;
/

CREATE SEQUENCE recenzii_id_recenzie_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER recenzii_id_recenzie_trg BEFORE
    INSERT ON recenzii
    FOR EACH ROW
    WHEN ( new.id_recenzie IS NULL )
BEGIN
    :new.id_recenzie := recenzii_id_recenzie_seq.nextval;
END;
/

CREATE SEQUENCE recenzii_id_produs_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER recenzii_id_produs_trg BEFORE
    INSERT ON recenzii
    FOR EACH ROW
    WHEN ( new.id_produs IS NULL )
BEGIN
    :new.id_produs := recenzii_id_produs_seq.nextval;
END;
/


--DROP TABLE clienti CASCADE CONSTRAINTS;
--DROP TABLE produse CASCADE CONSTRAINTS;
--DROP TABLE comenzi CASCADE CONSTRAINTS;
--DROP TABLE produse_comandate CASCADE CONSTRAINTS;
--DROP TABLE recenzii CASCADE CONSTRAINTS;
--DROP TABLE categorii_produse CASCADE CONSTRAINTS;
--DROP TABLE descierea_prod CASCADE CONSTRAINTS;
--DROP SEQUENCE categorii_produse_id_categorie;
--DROP SEQUENCE clienti_id_client_seq;
--DROP SEQUENCE comenzi_id_comanda_seq;
--DROP SEQUENCE produse_id_produs_seq;
--DROP SEQUENCE recenzii_id_recenzie_seq;
--DROP SEQUENCE recenzii_id_produs_seq;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
